### ISSUE TITLE
further languages (specifically Elm)

### ISSUE THREAD

**Issue by BrianHicks** [ul/kak-tree#16]
hello! Thanks for this lovely plugin!

I wonder if you're open to adding other languages, and what your standards of completeness are for them? Specifically I'm thinking about https://github.com/Razzeee/tree-sitter-elm, which http://tree-sitter.github.io/tree-sitter/ says is "fairly complete."

If it's super easy for you to add, would you mind? Otherwise, I'm happy to submit a patch but I'll be a bit. 😄

**Comment by ul** [comment]
Hey, thank you for kind words!

Yes, I'm totally open to adding new languages. They don't have to be complete as long as they compile and are in a somewhat useful state. We anyway feature-gate them so people can opt-out if they don't want the specific parser to be included in the build.

PR is welcome, feel free to ask any questions about the codebase or submit work-in-progress version for feedback.

**Comment by BrianHicks** [comment]
OK, about to do that!

**Comment by BrianHicks** [comment]
=> https://github.com/ul/kak-tree/pull/17
