### ISSUE TITLE
Add Clojure? - link included

### ISSUE THREAD

**Issue by bhougland18** [ul/kak-tree#18]
How can we get Clojure added? From asking around, it appears this project is the canonical Clojure Tree-sitter project: https://github.com/sogaiu/tree-sitter-clojure

Thanks!

**Comment by ul** [comment]
You can use this PR as an example: https://github.com/ul/kak-tree/pull/17
Essentially, you need to add a git submodule with the parser and then provide a mapping from filetype to parser guarded with a feature flag.

**Comment by ul** [comment]
Fixed in #20.
