### ISSUE TITLE
Kak-tree not working

### ISSUE THREAD

**Issue by eko234** [ul/kak-tree#27]
Sorry for the vague title, but I really do not get a clue about why, I'm loading the rc file generated when you build kak-tree with the source command, also tried in autoloads, I built it with javascript, ruby and clojure, when I check with the --do-you-understand command those languages I indeed get the 0 code return, but inside kakoune when I run tree-node-sexp I get just nothing, I also copied the config file on the readme, I'm not getting errors in the  debug buffer or anything.

Maybe I forgot to do something?

**Comment by eko234** [comment]
I'm using kakoune v2021.11.08 btw

**Comment by eko234** [comment]
Actually I found that kak-tree does logging and the path to the file is on the option tree_log, I this should appear in the readme, I'm getting 
```
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:44:35 
```

**Comment by eko234** [comment]
It means it cant load the config file... I think I can go on from here.

**Comment by eko234** [comment]
Beware the tree_cmd seems to not work with relative paths to the ~ symbol, so better set full paths.

**Comment by ul** [comment]
Indeed, `kak-tree` doesn't do any variables expansion in the path. But it should be possible to leverage shell itself for that in kakrc; something like `set global tree_cmd %sh{ echo ~/kak-tree.toml }` (or `set global tree_cmd %sh{ echo $HOME/kak-tree.toml }`) may help.
