### ISSUE TITLE
Cargo install results in binary only working with rust

### ISSUE THREAD

**Issue by JJK96** [ul/kak-tree#6]
I'm using rust 1.33.0-nightly.

When I do `cargo build --release --features "bash c cpp julia php python rust"`

I get a binary in `./target/release` that works with all those languages.

However, if I run `cargo install --path .` the installed binary and the binary in `./target/release` only work for rust. Note that I cannot simply run `cargo install` in this version of rust because of
```
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
```

This might be an issue with a newer rust version.

**Comment by ul** [comment]
Shame on me, I didn't test `cargo install` part. You might need to provide features option for this command (and skip the build part). I will test it once I get home and update README.
