### ISSUE TITLE
Unexpected lack of parents for expressions in python

### ISSUE THREAD

**Issue by danr** [ul/kak-tree#9]
Hi ul, I'm a bit puzzled why the python tree sitter does not go from expressions to statements. In the code below the parent nodes of the ones become `1 + 1` but the parent for that is not `return 1 + 1`.

```python
def test():
    return 1 + 1
```

I am expecting `return 1 + 1` to be the parent of `1 + 1`, but right now nothing happens with `tree-select-parent-node`.

**Comment by danr** [comment]
Oh it turns out that since you can return a tuple of values an `expression_list` node is introduced.
With this code the whole return statement becomes selected using `tree-select-parent`: 

```python
def test():
    return 1 + 1, 2
```

When there is only one element in that list it has the same span as its child. Is this why it's not getting
a proper parent? I'm suggesting that `tree-select-parent` should skip nodes that have the same range as 
the current selection.

**Comment by aecepoglu** [comment]
Having a similar issue

kak-tree cannot climb up from a node if it has a visually invisible parent.

Ocaml sample:

```ocaml
let a = 5
let b = a + 1
```

select `a` and try to go up to your parent. You can't.

The sexp of `let b = a + 1` is:

```
(value_definition
  (let_binding
    (value_name)
    (infix_expression
      (value_path (value_name))
      (infix_operator)
      (number) )))
```

**Comment by ul** [comment]
Thanks folks for reporting, I agree kak-tree should skip parent which have the same range as a child.

**Comment by ul** [comment]
Please feel free to reopen the issue if the latest master doesn't work for your case.

**Comment by aecepoglu** [comment]
Worked with the example I sent above.
Cheers
